version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.docker
    ports:
      - 80:80
    depends_on:
      - frontend
    volumes:
      - .:/var/www/frontend
  frontend:
    image: node:latest
    working_dir: /var/www/frontend
    volumes:
      - .:/var/www/frontend
    tty: true
